### ISSUE TITLE
[BUG] Can´t draw any Tinkers construct bows

### ISSUE THREAD

**Issue by Rafcamora** [AMPZNetwork/Fossilized#4]
**Describe the bug**
I´m currently playing the newest version of Fossilized and I´m unable to draw Tinkers Construct bows, longbows and crossbows while in survival mode. I´ve tried having vanilla arrows as well as TC arrows in my inventory but neither did anything to fix it. I tried to use the same bow in creative mode and it worked, back in survival it didn´t again. I tried other worlds and restarting everything. I couldn´t find anything online about this and no one in the modpack discord knows anything either. I tried deleting the whole modpack folder and doing a complete reinstall.
**To Reproduce**
1. Try using tinkers construct bows I guess?
**Expected behavior**
When rightclicking to draw the bows nothing happens in survival mode

**Crash Log**

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Win10 64bit
 - Fossilized Version 1.7.2b
 - Platform ATLauncher
 - Extra mods added by you: nothing extra

**Comment by Rafcamora** [comment]
Tried Fossilized through techniclauncher, same issue. Tried using version 1.7.1b same issue.

**Comment by LabsZero** [comment]
Thank you I shell look into the issue and try and patch it in V1.7.3b

**Comment by Rafcamora** [comment]
Also not working on the server, just a heads up. Strange that no one else found that already.
Thanks for the work!

**Comment by LabsZero** [comment]
Hi, from my testing it seems to be the mod itself. Your best bet is to report the issue to the mod author so they can try and fix it issue.

**Comment by LabsZero** [comment]
Good News this issue has been resolved in V2.1
